twig:
    file_name_pattern: "*.twig"
    date:
        format: "Y-m-d" # Canadian format
    form_themes:
        - "bootstrap_5_layout.html.twig"
        # - "form/form_theme.html.twig"

when@test:
    twig:
        strict_variables: true
