vich_uploader:
    db_driver: orm

    mappings:
        testimonial_image:
            uri_prefix: /uploads/testimonials
            upload_destination: '%kernel.project_dir%/public/uploads/testimonials'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        partnership_image:
            uri_prefix: /uploads/partnerships
            upload_destination: '%kernel.project_dir%/public/uploads/partnerships'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        mmm_image:
            uri_prefix: /uploads/mmm
            upload_destination: '%kernel.project_dir%/public/uploads/mmm'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        course_image:
            uri_prefix: /uploads/course
            upload_destination: '%kernel.project_dir%/public/uploads/course'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        course_certificate:
            uri_prefix: /uploads/certificates/templates
            upload_destination: '%kernel.project_dir%/public/uploads/certificates/templates'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
