vich_uploader:
    db_driver: orm

    mappings:
        testimonial_image:
            uri_prefix: /uploads/testimonials
            upload_destination: '%kernel.project_dir%/public/uploads/testimonials'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
